DOCS-14953: scala compatability tables
mongodb/docs-ecosystem pull request #784
Opened 2021-12-15 16:53 UTC by ccho-mongodb

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCS-14953

### Snooty build log:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61ba1cf2c52f2a460fd689f3

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodborg-staging.corp.mongodb.com/ecosystem/docsworker/NNNNN/index.html

### Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Does it render on staging correctly?
- [ ] Are all the links working?
- [ ] Are the staging and workerpool job links in the PR description updated?

2021-12-16 01:21 UTC, stIncMale commented
I see nothing referring to Scala version in the current version in the file `driver-scala/build.gradle`. In the file `build.gradle` there is `implementation ('org.scala-lang:scala-library:%scala-version%')`, but I don't see `scala-version` being defined anywhere. @rozza is probably the only one who can tell how to determine which Scala version the driver is compatible with, specifically the version 1.1 of the driver.

2021-12-16 14:58 UTC, rozza requested changes
Added some feedback with the requested changes.

@stIncMale fyi the scala versions we compile against are all in the [gradle.properties](https://github.com/mongodb/mongo-java-driver/blob/master/gradle.properties#L19) file

2021-12-16 16:19 UTC, ccho-mongodb commented on source/includes/language-compatibility-table-scala.rst
> -   * - 1.1
Thanks, I'll add the row back with the correct version.

2021-12-17 09:14 UTC, rozza approved these changes
LGTM!

2021-12-17 15:38 UTC, merged