DOCSP-26711: Update compat tables for PHPC and PHPLIB 1.15
mongodb/docs-ecosystem pull request #848
Opened 2022-11-28 09:54 UTC by jmikola

# Pull Request Info

JIRA - https://jira.mongodb.org/browse/DOCSP-26711

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?

2022-11-29 18:26 UTC, mongoKart requested changes
Two small suggestions. Note that docs-ecosystem/master already contains v1.15 but not v8.2 of the Driver, so the merge can accept either version in the conflict.

2022-11-29 18:26 UTC, mongoKart commented on source/includes/language-compatibility-table-php.rst
> +   * - ext + lib 1.15
Issue: We should probably keep a footnote similar to the current one to explain that 1) we skipped lib 1.14 and 2) the versions are now equivalent between lib and ext. I can update the footnote text in a different PR.

Suggestion:

```suggestion
   * - ext + lib 1.15 [#PHP1.15-version-parity]_
```

2022-11-30 04:35 UTC, jmikola commented on source/includes/language-compatibility-table-php.rst
> +   * - ext + lib 1.15 [#PHP1.15-version-parity]_
```suggestion

   * - ext + lib 1.15 [#PHP1.15-version-parity]_
```

2022-11-30 04:36 UTC, jmikola commented on source/includes/mongodb-compatibility-table-php.rst
> +   * - ext + lib 1.15 [#PHP1.15-version-parity]_
```suggestion

   * - ext + lib 1.15 [#PHP1.15-version-parity]_
```

2022-11-30 17:15 UTC, merged