Updating PHP libraries, 2023
mongodb/docs-ecosystem pull request #866
Opened 2023-04-04 13:59 UTC by techbelle

https://github.com/traderinteractive/mongo-queue-php has the wrong link, it links to a fork by a user rather than the main https://github.com/purekid/mongodm hasn't been updated since 2017, should be removed https://github.com/bjori/mongo-php-transistor hasnt been updated since 2016, should be removed https://github.com/mongator/mongator/ hasn't been updated since 2014, should be removed https://github.com/aleksmitov/MongoFilesystem hasn't been updated since 2015, should be removed https://github.com/mongofill/mongofill has been archived and isn't maintained since 2016, removing  Adding https://github.com/PHPSocialNetwork/phpfastcache  Adding XHGUI

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-ecosystem/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2023-04-05 13:29 UTC, ccho-mongodb requested changes
Thanks for the updates @techbelle! Please take a look at the suggested fixes and re-request a review once updated.

2023-04-05 13:29 UTC, ccho-mongodb commented on source/php-libraries.txt
> +high-performance backend cache system for MongoDB.
Bullet points that span multiple lines need to match indentation, similar to the formatting of the previous bullet point.

```suggestion
- `PHPfastcache <https://github.com/PHPSocialNetwork/phpfastcache>`_ provides a simple,
  high-performance backend cache system for MongoDB.
```

2023-04-05 13:29 UTC, ccho-mongodb commented on source/php-libraries.txt
> +storing it in MongoDB
- Fixed indentation
- Fixed capitalization
- I think the rewording of the sentence explains the functionality of XHGui and XHProf a little better.

```suggestion
- `XHGui <https://github.com/perftools/xhgui>`_, a web interface for the XHProf profiler
  that stores profiling data in MongoDB.
```

2023-04-05 14:02 UTC, techbelle commented
ok thank you! i am still getting familiar with the syntax on these sorts of files 👍

2023-04-10 20:40 UTC, ccho-mongodb approved these changes
LGTM

2023-04-14 19:54 UTC, merged